### ISSUE TITLE
Populating Invocation Logs

### ISSUE THREAD

**Issue by ThePoShWolf** [KarlGW/azfunc#40]
I unfortunately spent several hours figuring out how to get Go working with a custom handler in Azure before finding your awesome library, thank you!

Using `azfunc`, I haven't been able to determine how to populate the `Logs` property in the response to the functions host, is that supported? The string array in the `Logs` property is used to populate the invocation logs on the function app.

For reference: [Custom Handler Response Payload](https://learn.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers#response-payload)

**Comment by KarlGW** [comment]
Thanks for the kind words @ThePoShWolf!

At this moment is isn't supported, as during all my use of custom handlers in various forms (from long before the library was created) I never had use of it and instead relied on output logging that is captured by application insights (or other options that captures output logs). Logging with the built-in logger (based on `log/slog`) is done like so:

```
ctx.Log().Info(msg, args...)
ctx.Log().Error(msg, args...)
ctx.Log().Debug(msg, args...)
ctx.Log().Warn(msg, args...)
```

If there is a need to also support setting the logs property on the response to the function host I can look into it.

**Comment by ThePoShWolf** [comment]
Yeah, that totally makes sense. I am also using app insights as you have suggested.

If it were implemented, I would definitely use it and can help test, if you are interested. Thanks!

**Comment by KarlGW** [comment]
This have now been resolved with pull request #41  and thus release v0.20.0.

As stated in my previous comment it is used through:
`ctx.Outputs.Log()` and from there exposes:
`Debug`, `Error`, `Info` and `Warn` for structured log messages to the log slice. In addition to this method `Write` is also provided to write a "custom" string without formatting or extra fields.

**Comment by ThePoShWolf** [comment]
Thank you! I've tested it and can confirm that it works. The only comment I have is that if it were to function like the native handlers, logging should output to both places by default. If I use both forms then they both end up in the app insights log, with the output logs showing up all at the end of the execution.

**Comment by KarlGW** [comment]
@ThePoShWolf I think that is gonna be a problem with how custom handlers work.

The logs put in the outputs `Logs` field, will only be processed after the function has finished executing (by how custom handlers are designed). If the stdout/stderr logs would also put it into this field (that is in both places), there would be duplicate entries in application insights. First they will be logged at the call to `ctx.Log()...` and would be processed by application insights. And then once again it would be processed due to existing in the `Logs` field when the function has returned the response to the function host.

Or did I not understand your request properly and am misunderstanding you?

**Comment by ThePoShWolf** [comment]
Oooh, I see what you mean. Even if it was one unified method that output the logs to stdout/stderr and passed them back to the function host, it would still duplicate the logs in app insights because the function host also outputs the string array from the `Logs` return property.

After looking through the azure-function-host repository, I found that there are at least a few other folks complaining about logging from custom handlers and I don't see much of a response from Microsoft, so oh well.

Thank you for this library and your quick turnaround on my request! Implementing `azfunc` has saved me quite a bit of complexity.

**Comment by KarlGW** [comment]
@ThePoShWolf it has been my pleasue. I am glad you have found use for this library. Don't hesitate to add new issues if you feel there are other features missing (or needed)!
